### ISSUE TITLE
No default formatter for Float type ?

### ISSUE THREAD

**Issue by albert-kam** [beranradek/formio#12]
In BasicFormatters i noticed that Float type support is missing. 

Is there a way to have set the formatter globally for the type of Float ?

Thank you.

**Comment by beranradek** [comment]
You can extend BasicFormatters as it is shown at http://www.formio.net/documentation/configuration/ and register it using formatters method when building form Config object. I can also improve the library to involve the Float type in default settings (also pull request is welcomed).

**Comment by albert-kam** [comment]
How did i miss that ? Thank you. A very well designed library btw.
