### ISSUE TITLE
How to add Bean Validation 2.0 ClockProvider ?

### ISSUE THREAD

**Issue by albert-kam** [beranradek/formio#13]
Hi again !

I'm using `@Past` and `@PastOrFuture` on my OffsetDateTime fields, and found out it's not validating correctly, with `@Past` passes validation when choosing current date. 

My assumption why this happens is that because in my custom OffsetDateTimeFormatter, i convert the user inputted date with Asia/Jakarta timezone into UTC, therefore the date field changes from 'today' to 'yesterday', since Asia/Jakarta is 'faster' by 7 hours.

So the next assumption here is that `@Past` compares with `now()` using default timezone configured in my system. And to solve this, it means i need to tell the validator about my timezone.

My exploration tells me that i need to pass the ClockProvider instance, like detailed in hibernate validator documentation:
https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#section-clock-provider
```

ValidatorFactory validatorFactory = Validation.byDefaultProvider()
        .configure()
        .clockProvider( new FixedClockProvider( ZonedDateTime.of( 2016, 6, 15, 0, 0, 0, 0, ZoneId.of( "Europe/Paris" ) ) ) )
        .buildValidatorFactory();
Validator validator = validatorFactory.getValidator();
```

How do i achieve this in formio ? Thank you.

**Comment by beranradek** [comment]
Hi Albert!

You can set beanValidator when creating custom form configuration (http://www.formio.net/documentation/configuration/). Use instance of DefaultBeanValidator with your specific ValidatorFactory passed to its constructor (see https://github.com/beranradek/formio/blob/a835cb530cc7a53eabb6b4dd2bdb93a010a3d0a2/src/main/java/net/formio/Config.java#L275 where DefaultBeanValidator is constructed as an example).

**Comment by albert-kam** [comment]
Thank you, this works great.

Although i still could not get my intention to work.
I posted my situation with a junit here at SO: https://stackoverflow.com/questions/60341963/current-datetime-shouldnt-pass-the-validation-using-past-annotation

Thank you, as always !
