### ISSUE TITLE
Localized number input

### ISSUE THREAD

**Issue by albert-kam** [beranradek/formio#14]
Hi again !

I want to be able to input 40000, or 40.000 and have 40000d value in my form instance.

So i added this:
```
Forms.basic(type, prefix)
	    .fields(fields)
            .build(Forms.config()
                .messageBundleName(dataClass.getName().replace(".", "/"))
                .location(LOCATION)
                .formatters(FORMATTERS)
                .beanValidator(BEAN_VALIDATOR)
                .build());

```
where my LOCATION is 
```
Location.getInstance(new Locale("id", "ID"), TimeZone.getTimeZone(ZoneId.of("Asia/Jakarta")));
```

But when i tried inputting 40.000, it binds as 40.
I tried 40,000 also, but it binds as 40.

I notice there's a formatPattern in Formatter's ```parseFromString```, maybe it has something to do with it ?
But i couldnt find any related configuration for this formatPattern.

Any pointers would be greatly appreciated.

**Comment by beranradek** [comment]
Hi albert,

can you please try to set pattern as described in the first table at https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html and possibly debug net.formio.format.FormatsCache#getOrCreateDecimalFormat for your case?

**Comment by albert-kam** [comment]
Hi beranradek,

Actually this is where i'm confused, where do i set the pattern ?

Thank you !

**Comment by beranradek** [comment]
You can specify the pattern as described in http://www.formio.net/documentation/ (Custom form field specification). Pattern is one of the properties of FieldProps class that serves for building a FormField (using Form.field(...).pattern(...)).

**Comment by albert-kam** [comment]
And i missed it again, hahaha ... Sorry and Thank you for the pointers !
Let me try and put in a working example later on in here.

**Comment by albert-kam** [comment]
Mostly i am using `Forms.basic()` as it is good enough for me. 
With that, is there a global setting for the default pattern to use in `Forms.basic()` if not specified explicitly for each field ?

**Comment by albert-kam** [comment]
I just got back to this issue, and finally i replaced the default bigdec formatter in BasicFormatters with my own impl. 
This way Forms.basic() will work fine as my pattern is hardcoded in the custom bigdec formatter for the whole app.
Thank you for your pointers !
