### ISSUE TITLE
BasicFormatters.registerFormatters longFormatter broken; uses byteValue instead of longValue

### ISSUE THREAD

**Issue by matthewshannon** [beranradek/formio#9]
final Formatter<Long> longFormatter = new Formatter<Long>() {

				@Override
				public Long parseFromString(String str, Class<Long> destClass,
						String formatPattern, Location loc) {
					try {
						String amendedStr = removeDecimalPart(str, loc.getLocale());
						return Long.valueOf(FormatsCache.getOrCreateDecimalFormat(formatPattern, loc)
							.parse(amendedStr).byteValue());
					} catch (Exception ex) {
						throw new StringParseException(Long.class, str, ex);
					}
				}

				@Override
				public String makeString(Long value, String formatPattern, Location loc) {
					return COMMON_STR_MAKER.makeString(value, formatPattern, loc);
				}

			};
			formatters.put(Long.class, longFormatter);
			formatters.put(long.class, longFormatter);

**Comment by beranradek** [comment]
Thanks for reporting this issue, Matthew. Fix is available in new version 1.6.3.
